Voice Over added into MainView and ListCard
MarinaFX/EasyRancho pull request #92
Opened 2021-11-09 20:10 UTC by luizmellodev

Voice Over created into MainView and ListCard

2021-11-09 20:20 UTC, thaisrfernandes commented on Superlista/Service/DataService.swift
> +                print(list.name)
rm comment

2021-11-09 20:20 UTC, thaisrfernandes commented on Superlista/Views/MainView.swift
> +                                    .accessibility(addTraits: .isButton)
rm trait

2021-11-09 20:30 UTC, thaisrfernandes requested changes

2021-11-09 20:30 UTC, thaisrfernandes commented on Superlista/Components/ListCard.swift
> +                        .accessibility(label: Text("Remover lista selecionada"))
Criar localizables

2021-11-09 20:30 UTC, thaisrfernandes commented on Superlista/Components/ListCard.swift
> +                        .accessibility(hint: Text("Removerá a lista selecionada"))
Criar localizables

2021-11-09 20:30 UTC, thaisrfernandes commented on pt-BR.lproj/Localizable.strings
Adicionar localizables em todos os arquivos.

2021-11-11 17:35 UTC, luizmellodev commented on Superlista/Components/ListCard.swift
> +                        .accessibility(label: Text("Remover lista selecionada"))
feito 🆗

2021-11-11 18:07 UTC, thaisrfernandes approved these changes

2021-11-11 18:07 UTC, merged