Tk137
MarinaFX/EasyRancho pull request #98
Opened 2021-11-11 20:27 UTC by gabizorzo

2021-11-11 20:33 UTC, thaisrfernandes requested changes

2021-11-11 20:33 UTC, thaisrfernandes commented on Superlista/Service/CKService.swift
> +        print("upload users list")
rm print

2021-11-11 20:33 UTC, thaisrfernandes commented on Superlista/Service/CKService.swift
> +            if error == nil {
é safe usar esses force unwraps no record?

2021-11-11 20:34 UTC, gabizorzo commented on Superlista/Service/CKService.swift
> +            if error == nil {
sim, porque se error != nil, é porque tem record

2021-11-12 01:53 UTC, thaisrfernandes approved these changes

2021-11-12 17:19 UTC, MarinaFX commented
Em homenagem a ti Gabi

O que aconteceu com o engenheiro quando ele se olhou no espelho?
O Engenheiro Civil 

<img src="https://c.tenor.com/nMFJtuIDTaMAAAAd/eduardo-sterblitch.gif" alt="hehehe" width="200"/>

2021-11-12 17:19 UTC, merged